# Generated by Django 3.2.4 on 2021-06-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
                ('friendly_name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=50, unique=True)),
                ('entity_type', models.CharField(max_length=10)),
                ('fetched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('image', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('subscribers', models.IntegerField(default=0)),
            ],
        ),
    ]
