# Generated by Django 3.2.4 on 2021-06-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_entity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='app_icon_id',
            field=models.IntegerField(default=0),
        ),
    ]
