# Generated by Django 3.2.4 on 2021-06-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_app_icon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='app_icon_id',
            field=models.CharField(default=0, max_length=35),
        ),
    ]
