# Generated by Django 3.2.4 on 2021-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_category_app_icon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(default=True, max_length=15)),
            ],
        ),
    ]
